const SEARCH_OPERATOR = {
    CONTAINS: "CONTAINS",
    ENDWITH: "ENDWITH",
    EQUAL: "EQUAL",
    GREATER: "GREATER",
    GREATEROREQUAL: "GREATEROREQUAL",
    ISNOTNULL: "ISNOTNULL",
    ISNULL: "ISNULL",
    LESSER: "LESSER",
    LESSEROREQUAL: "LESSEROREQUAL",
    NOTEQUAL: "NOTEQUAL",
    STARTWITH: "STARTWITH",
} as const;

export type ISearchConditionOperator = typeof SEARCH_OPERATOR[keyof typeof SEARCH_OPERATOR];

export { SEARCH_OPERATOR };
