const formStyleClassNames = {
    actions: "mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end",
    choiceControl: "mt-0.5 size-4 shrink-0 border-input p-0 shadow-none accent-primary",
    choiceDescription: "text-xs text-muted-foreground",
    choiceGroupHorizontal: "flex flex-wrap gap-4",
    choiceGroupVertical: "space-y-3",
    choiceItem: "flex items-start gap-3",
    choiceLabelText: "text-sm font-medium leading-5 text-[var(--text-main)]",
    choiceTextBlock: "space-y-1",
    detailCard: "rounded-md border border-[var(--border)] bg-[var(--bg-surface)] p-4",
    detailGrid: "grid gap-5 md:grid-cols-2 xl:grid-cols-3",
    detailLabel: "text-xs font-semibold uppercase tracking-[0.14em] text-[var(--text-muted)]",
    detailValue: "mt-2 text-sm font-medium text-[var(--text-main)]",
    fieldCount: "text-xs text-muted-foreground",
    fieldContainer: "space-y-2",
    fieldDescription: "mt-1 block text-xs text-muted-foreground",
    fieldSpan6: "col-span-1 md:[grid-column:span_6/span_6]",
    fieldSpan8: "col-span-1 md:[grid-column:span_8/span_8]",
    fieldSpan12: "col-span-1 md:[grid-column:span_12/span_12]",
    fieldSpan24: "col-span-1 md:[grid-column:span_24/span_24]",
    fileInput: "h-auto cursor-pointer py-2",
    fileSummary: "block text-xs text-muted-foreground",
    form: "space-y-6",
    formGrid: "grid gap-5 md:grid-cols-2",
    helperText: "mt-2 block text-xs text-muted-foreground",
    inlineFieldActions: "flex gap-2 md:pt-[2px]",
    inlineFieldInput: "flex-1",
    inlineFieldLayout: "flex flex-col gap-3 md:flex-row md:items-start",
    inlineFieldSection: "md:col-span-2",
    lineItemErrors: "space-y-1 rounded-md border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive",
    lineItemGrid: "gap-0",
    lineItemSection: "space-y-4",
    radioControl: "rounded-full",
    sectionDescription: "text-sm text-muted-foreground",
    sectionDivider: "my-6 h-px bg-[var(--border)]",
    sectionGrid: "grid grid-cols-1 gap-5 md:[grid-template-columns:repeat(24,minmax(0,1fr))]",
    sectionHeading: "mb-4 space-y-1",
    sectionTitle: "text-xs font-semibold uppercase tracking-[0.18em] text-[var(--text-muted)]",
    selectTrigger: "w-full",
    switchButton: "h-auto w-full justify-start gap-3 px-3 py-2 text-left",
    switchContent: "flex min-w-0 flex-1 flex-col items-start gap-1",
    switchStateText: "text-xs text-muted-foreground",
    switchText: "text-sm font-medium text-[var(--text-main)]",
    switchThumb: "absolute left-0.5 size-5 rounded-full bg-background shadow-sm transition-transform",
    switchThumbChecked: "translate-x-5",
    switchTrack: "relative inline-flex h-6 w-11 shrink-0 items-center rounded-full bg-muted transition-colors",
    switchTrackChecked: "bg-primary",
};

export { formStyleClassNames };
